-- MySQL Script generated by MySQL Workbench
-- Tue Jan 25 12:35:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pipeorgan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pipeorgan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pipeorgan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pipeorgan` ;

-- -----------------------------------------------------
-- Table `pipeorgan`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`files` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `filename` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `fileable_id` BIGINT UNSIGNED NOT NULL,
  `fileable_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `class` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `creator` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 80660
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`instruments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `country` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `public` TINYINT(1) NOT NULL DEFAULT '0',
  `monument` TINYINT(1) NOT NULL DEFAULT '0',
  `organization_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `owner_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `physical_owner_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `mentor_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `primary_image_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `location_image_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `monument_number` VARCHAR(255) NULL DEFAULT NULL,
  `organ_number` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `instruments_organization_id_foreign` (`organization_id` ASC) VISIBLE,
  INDEX `instruments_owner_id_foreign` (`owner_id` ASC) VISIBLE,
  INDEX `instruments_mentor_id_foreign` (`mentor_id` ASC) VISIBLE,
  INDEX `instruments_physical_owner_id_foreign` (`physical_owner_id` ASC) VISIBLE,
  INDEX `instruments_primary_image_id_foreign` (`primary_image_id` ASC) VISIBLE,
  INDEX `instruments_location_image_id_foreign_idx` (`location_image_id` ASC) VISIBLE,
  CONSTRAINT `instruments_mentor_id_foreign`
    FOREIGN KEY (`mentor_id`)
    REFERENCES `pipeorgan`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `instruments_organization_id_foreign`
    FOREIGN KEY (`organization_id`)
    REFERENCES `pipeorgan`.`organizations` (`id`),
  CONSTRAINT `instruments_owner_id_foreign`
    FOREIGN KEY (`owner_id`)
    REFERENCES `pipeorgan`.`users` (`id`),
  CONSTRAINT `instruments_physical_owner_id_foreign`
    FOREIGN KEY (`physical_owner_id`)
    REFERENCES `pipeorgan`.`users` (`id`),
  CONSTRAINT `instruments_primary_image_id_foreign`
    FOREIGN KEY (`primary_image_id`)
    REFERENCES `pipeorgan`.`files` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `instruments_location_image_id_foreign`
    FOREIGN KEY (`location_image_id`)
    REFERENCES `pipeorgan`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 68544
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`builders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`builders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `city` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `country` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `extra_information` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `website` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `active_from` DATE NULL DEFAULT NULL,
  `active_till` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`dispositions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`dispositions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `estimate_date` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `history` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `instrument_id` BIGINT UNSIGNED NOT NULL,
  `builder_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `dispositions_instrument_id_foreign` (`instrument_id` ASC) VISIBLE,
  INDEX `dispositions_builder_id_foreing_idx` (`builder_id` ASC) VISIBLE,
  CONSTRAINT `dispositions_instrument_id_foreign`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `pipeorgan`.`instruments` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `dispositions_builder_id_foreing`
    FOREIGN KEY (`builder_id`)
    REFERENCES `pipeorgan`.`builders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1304
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`couplers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`couplers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`additional_specifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`additional_specifications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `system_console` ENUM('mechanical', 'pneumatic', 'electrical', 'electro pneumatic') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `system_playing_aids` ENUM('mechanical', 'pneumatic', 'electrical', 'electro pneumatic') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `system_stop_action` ENUM('mechanical', 'pneumatic', 'electrical', 'electro pneumatic') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `wind_system` ENUM('wedge-bellows', 'reservoir-bellows', 'feeder-bellows') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `console_description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `paying_aids_description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `wind_system_description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `pitch` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `temperature` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `console_location` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `disposition_id` BIGINT UNSIGNED NOT NULL,
  `coupler_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `particularities` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `additional_specifications_disposition_id_foreign` (`disposition_id` ASC) VISIBLE,
  INDEX `additional_specifications_coupler_id_foreign_idx` (`coupler_id` ASC) VISIBLE,
  CONSTRAINT `additional_specifications_disposition_id_foreign`
    FOREIGN KEY (`disposition_id`)
    REFERENCES `pipeorgan`.`dispositions` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `additional_specifications_coupler_id_foreign`
    FOREIGN KEY (`coupler_id`)
    REFERENCES `pipeorgan`.`couplers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 139
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`countries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `code` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `region` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `sub-region` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `intermediate-region` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`people` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `function` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `extra_information` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `website` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `date_of_death` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`addresses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `city` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `state` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `zip` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `instrument_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `organization_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `person_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `country_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `house_number` INT NOT NULL,
  `lat` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `long` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `addresses_instrument_id_foreign` (`instrument_id` ASC) VISIBLE,
  INDEX `addresses_organization_id_foreign` (`organization_id` ASC) VISIBLE,
  INDEX `addresses_person_id_foreign` (`person_id` ASC) VISIBLE,
  INDEX `addresses_country_id_foreign` (`country_id` ASC) VISIBLE,
  CONSTRAINT `addresses_country_id_foreign`
    FOREIGN KEY (`country_id`)
    REFERENCES `pipeorgan`.`countries` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `addresses_instrument_id_foreign`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `pipeorgan`.`instruments` (`id`),
  CONSTRAINT `addresses_organization_id_foreign`
    FOREIGN KEY (`organization_id`)
    REFERENCES `pipeorgan`.`organizations` (`id`),
  CONSTRAINT `addresses_person_id_foreign`
    FOREIGN KEY (`person_id`)
    REFERENCES `pipeorgan`.`people` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`archives` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `category` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `date_of_publication` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `link` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ISBN` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `more_information` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `number_of_pages` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `pages` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `publisher` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `title_of_chapter` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `public` TINYINT(1) NOT NULL DEFAULT '0',
  `organization_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `owner_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `archives_organization_id_foreign` (`organization_id` ASC) VISIBLE,
  INDEX `archives_owner_id_foreign` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `archives_organization_id_foreign`
    FOREIGN KEY (`organization_id`)
    REFERENCES `pipeorgan`.`organizations` (`id`),
  CONSTRAINT `archives_owner_id_foreign`
    FOREIGN KEY (`owner_id`)
    REFERENCES `pipeorgan`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 575
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`archive_instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`archive_instrument` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `archive_id` BIGINT UNSIGNED NOT NULL,
  `instrument_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `pages` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `archive_instrument_archive_id_foreign` (`archive_id` ASC) VISIBLE,
  INDEX `archive_instrument_instrument_id_foreign` (`instrument_id` ASC) VISIBLE,
  CONSTRAINT `archive_instrument_archive_id_foreign`
    FOREIGN KEY (`archive_id`)
    REFERENCES `pipeorgan`.`archives` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `archive_instrument_instrument_id_foreign`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `pipeorgan`.`instruments` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 582
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`manuals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`manuals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `range` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `wind_pressure` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `windchest_system` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `disposition_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `manuals_disposition_id_foreign` (`disposition_id` ASC) VISIBLE,
  CONSTRAINT `manuals_disposition_id_foreign`
    FOREIGN KEY (`disposition_id`)
    REFERENCES `pipeorgan`.`dispositions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2778
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pipeorgan`.`stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipeorgan`.`stops` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `partition` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `value` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `voices` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `manual_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `stops_manual_id_foreign` (`manual_id` ASC) VISIBLE,
  CONSTRAINT `stops_manual_id_foreign`
    FOREIGN KEY (`manual_id`)
    REFERENCES `pipeorgan`.`manuals` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20685
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
