PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>

CONSTRUCT { ?S ?P ?O } { 
	SERVICE <x-sparql-anything:> {
		BIND ( CONCAT( "./samples/Polifonia_-_organ_encyclopaedia_documents/" , ?_filename ) AS ?location )
		.
		fx:properties fx:location ?location .
		?S ?P ?O .

	}	
}