PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX organ: <http://w3id.org/polifonia/resource/organs/>
PREFIX oont: <http://w3id.org/polifonia/ontology/organs/>

CONSTRUCT
  {
	?organ a oont:Organ ;
		oont:builder ?builder ;
		oont:consolelocation ?originallocation ;
    # ?s ?p ?o .
  }
WHERE
  { SERVICE <x-sparql-anything:file:./output/history_base.json>
    { 
		fx:properties
				# fx:json.path "$..*" .
                # fx:json.path  "$[?(@.builder==\"Peter Gerritsz\")]" .
				fx:json.path.1 "$..Part01_001MIDDE..builder" ;
				fx:json.path.2 "$..Part01_001MIDDE..originallocation" .
				# fx:json.path.3 "$..Part01_001MIDDE..year" .
				
			[] a fx:root; 
			rdf:_1 ?builder ;
			rdf:_2 ?originallocation .
			# rdf:_3 ?year .
		# BIND (?builder AS ?s ) .
		BIND ("?organ" AS ?organ) .
		# BIND (?originallocation AS ?o) .

		# ?s  ?p  ?o 
	} 
  }