PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX organ: <http://w3id.org/polifonia/resource/organs/>
PREFIX oont: <http://w3id.org/polifonia/ontology/organs/>

CONSTRUCT {
	?organ a oont:Organ ;
		rdfs:label ?title ;
		oont:name ?title ;
		oont:year ?year
} WHERE { 
		{
			SERVICE <x-sparql-anything:> {
				BIND( CONCAT("./samples/Polifonia_-_organ_encyclopaedia_documents/", ?_file )  AS ?location) .
				fx:properties fx:location ?location ; 
				fx:archive.matches ".*\\.docx" .
				[] a fx:root; rdf:_1/rdf:_1 ?match .
		
				BIND ( replace( ?match, "@K1:", "") AS ?match1 ) .
				BIND ( replace( ?match1, "\\[x1\\]", "") AS ?match2 ) .
				BIND ( replace( ?match2, "\\[K1\\]", "") AS ?match3 ) .
				BIND ( fx:String.toLowerCase( ?_id ) AS ?id)
			}	
		} 
		.

		{
			?val apf:strSplit ( ?match3 "/" ) . 
			BIND ( fx:serial("title") as ?check ) .
			FILTER ( ?check = 1 ) .
			BIND ( ?val as ?title ) .
		} UNION {
			?val apf:strSplit ( ?match3 "/" ) . 
			BIND ( fx:serial("year") as ?check ) .
			FILTER ( ?check = 2 ) .
			BIND ( ?val as ?year ) .
		} 
		.
		BIND ( IRI ( CONCAT ( STR(organ:), ?id ) ) as ?organ ) .

#		BIND ( ?val AS ?title )	
#		?val2 apf:strSplit ( ?match3 "/" ) . 
#		BIND (fx:serial() as ?check2)
#		FILTER ( ?check2 = 2 ) .
#		BIND ( ?val2 AS ?year )	

	}

