PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX organ: <http://w3id.org/polifonia/resource/organs/>
PREFIX oont: <http://w3id.org/polifonia/ontology/organs/>

# evaluate using size of files, no. service calls, files queried. 

CONSTRUCT
  {
	?organ a oont:Organ ;
		oont:builder ?builder ;
		oont:consolelocation ?originallocation ;
		oont:dateOfBirth ?dateOfBirth ;
		oont:monument ?building ;
		oont:monumentNumber ?monumentNumber ;
		oont:name ?organName ;
		oont:organNumber ?organNumber ;
		oont:state ?state ;
		oont:systemPlayingAids ?systemPlayingAids ;
		oont:pitch ?pitch ;
		oont:range1 ?range ; # remove when compoundstop.json range is added?
		oont:temperature ?temperature ;
		oont:windPressure ?windPressure ;
		oont:windSystem ?windSystem ;
	.

	?disposition xyz:divisionName ?divisionname . # xyz
	?disposition oont:partition ?partition .
	?disposition oont:AdditionalSpecification ?specification .

	?change oont:date ?datechange .
	?change oont:AdditionalSpecification ?description . 
	?change oont:Builder ?builder .
  }
WHERE
  { SERVICE <x-sparql-anything:file:./output/history_base.json>
    { 
		BIND(CONCAT("$.", ?_organ, ".builder") AS ?organBuilder) .
		BIND(CONCAT("$.", ?_organ, ".originallocation") AS ?organOriginalLocation) .
		BIND(CONCAT("$.", ?_organ, ".year") AS ?organDob) .

		fx:properties
				fx:json.path.1 ?organBuilder ;
				fx:json.path.2 "$.Part01_001MIDDE.originallocation" ; #doesnt work for the ?organOriginalLocation
				fx:json.path.3 "$.Part01_001MIDDE.year" ; #doesnt work for ?organDob
				. 
				
			[] a fx:root; 
			rdf:_1 ?builder ;
			rdf:_2 ?originallocation ;
			rdf:_3 ?dateOfBirth ; 
			.

		BIND (?_organ AS ?organ) .
	} 
	SERVICE <x-sparql-anything:file:./output/base.json>
    { 
		BIND(CONCAT("$.", ?_organ, ".building") AS ?organBuilding) .

		fx:properties
				fx:json.path.1 ?organBuilding ;
				fx:json.path.2 "$.Part01_001MIDDE.monumentnumber" ;
				fx:json.path.3 "$.Part01_001MIDDE.name" ; 
				fx:json.path.4 "$.Part01_001MIDDE.organnumber" ; 
				fx:json.path.5 "$.Part01_001MIDDE.place" ; 
				.
				
			[] a fx:root; 
			rdf:_1 ?building ;
			rdf:_2 ?monumentNumber ;
			rdf:_3 ?organName ; 
			rdf:_4 ?organNumber ;
			rdf:_5 ?state ;
			.
	} 
	SERVICE <x-sparql-anything:file:./output/tech.json>
    { 
		fx:properties
				fx:json.path.1 "$.Part01_001MIDDE.aids" ;
				fx:json.path.2 "$.Part01_001MIDDE.pitch" ;
				fx:json.path.3 "$.Part01_001MIDDE.range1" ; 
				fx:json.path.4 "$.Part01_001MIDDE.temperature" ; 
				fx:json.path.5 "$.Part01_001MIDDE.windPres" ; 
				fx:json.path.6 "$.Part01_001MIDDE.windSys" ; 
				.
				
			[] a fx:root; 
			rdf:_1 ?systemPlayingAids;
			rdf:_2 ?pitch ; 
			rdf:_3 ?range ;
			rdf:_4 ?temperature ;
			rdf:_5 ?windPressure ;
			rdf:_6 ?windSystem ;
			.
	} 
	SERVICE <x-sparql-anything:file:./output/dispositions.json> 
	{
		fx:properties
			fx:json.path.1 "$.Part01_001MIDDE.dispositions[?(@.current==true)].description";
			fx:json.path.2 "$.Part01_001MIDDE.dispositions[?(@.current==true)].disposition[0].division_name";
			fx:json.path.3 "$.Part01_001MIDDE.dispositions[?(@.current==true)].disposition[0].stoplist[0].partition";
			fx:json.path.4 "$.Part01_001MIDDE.dispositions[?(@.current==true)].disposition[0].stoplist[0].spec";
			.

		[] a fx:root; 
			rdf:_1 ?disposition ;
			rdf:_2 ?divisionname ;
			rdf:_3 ?partition ;
			rdf:_4 ?specification ;
	}
	SERVICE <x-sparql-anything:file:./output/history_projects.json>  
	{
		fx:properties
			fx:json.path.1 "$.Part01_001MIDDE[0].changes[0]";
			fx:json.path.2 "$.Part01_001MIDDE[0].date";	
			fx:json.path.3 "$.Part01_001MIDDE[0].description";	
			fx:json.path.4 "$.Part01_001MIDDE[0].name";	
			.

		[] a fx:root; 
			rdf:_1 ?change ;
			rdf:_2 ?datechange ;	
			rdf:_3 ?description ;
			rdf:_4 ?builder ;	
	}
  }